# Generated by Django 5.2.10 on 2026-01-31 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='business_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_orderer', to=settings.AUTH_USER_MODEL),
        ),
    ]
