# Generated by Django 5.2.10 on 2026-02-11 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='offerdetail',
            constraint=models.UniqueConstraint(fields=('offer', 'offer_type'), name='unique_offer_type_per_offer'),
        ),
    ]
